easy_admin:
    entities:
        # List the entity class name you want to manage
        Cantine:
            class: App\Entity\Cantine
            list:
                fields:
                    - name
                    - administrateur
                    - phone
                    - adresse
                    - code_postal
                    - ville
                    - menus


        User:
            class: App\Entity\User
            list:
                fields:
                    - { property: 'email', type: 'email' }
                    - cantine
                    - adminCantine
                    - menu
                    - menuSelectionnes
                    - enabled

        Entree:
            class: App\Entity\Entree
            list:
                fields:
                    - name
                    - description
                    - { property: 'image', type: 'image', base_path: '/img/entrees/'}
                    - menu
                    - {property: 'Tarif', label: 'Tarif (€)'}

        Plat:
            class: App\Entity\Plat
            list:
                fields:
                    - name
                    - description
                    - { property: 'image', type: 'image', base_path: '/img/plats/'}
                    - menu
                    - {property: 'Tarif', label: 'Tarif (€)'}

        Accompagnement:
            class: App\Entity\Accompagnement
            list:
                fields:
                    - name
                    - description
                    - { property: 'image', type: 'image', base_path: '/img/accompagnements/'}
                    - menu
                    - {property: 'Tarif', label: 'Tarif (€)'}

        Dessert:
            class: App\Entity\Dessert
            list:
                fields:
                    - name
                    - description
                    - { property: 'image', type: 'image', base_path: '/img/desserts/'}
                    - menu
                    - {property: 'Tarif', label: 'Tarif (€)'}

        Menu:
            class: App\Entity\Menu
            form:
                fields:
                    - date
                    - cantine
                    - { property: 'entrees', type_options: { multiple: true, by_reference: false }}
                    - { property: 'plats', type_options: { multiple: true, by_reference: false }}
                    - { property: 'accompagnements', type_options: { multiple: true, by_reference: false }}
                    - { property: 'desserts', type_options: { multiple: true, by_reference: false }}
                    - users


        MenuSelectionne:
            class: App\Entity\MenuSelectionne

    design:
        assets:
            favicon: '/img/backend/appli/four-couteau.png'


    site_name: '<img style="float:right" src="/img/backend/appli/four-couteau.png" /><p>Bienvenue sur le Gestionnaire de</p><b>Cantine 0 Gaspi</b>'