easy_admin:
    entities:
        # List the entity class name you want to manage
        Cantine:
            class: App\Entity\Cantine

        User:
            class: App\Entity\User

        Entree:
            class: App\Entity\Entree
            list:
                fields:
                    - name
                    - description
                    - { property: 'image', type: 'image', base_path: '/img/entrees/'}
                    - menu

        Plat:
            class: App\Entity\Plat
            list:
                fields:
                    - name
                    - description
                    - { property: 'image', type: 'image', base_path: '/img/plats/'}
                    - menu

        Accompagnement:
            class: App\Entity\Accompagnement
            list:
                fields:
                    - name
                    - description
                    - { property: 'image', type: 'image', base_path: '/img/accompagnements/'}
                    - menu

        Dessert:
            class: App\Entity\Dessert
            list:
                fields:
                    - name
                    - description
                    - { property: 'image', type: 'image', base_path: '/img/desserts/'}
                    - menu

        Menu:
            class: App\Entity\Menu
            form:
                fields:
                    - name
                    - date
                    - cantine
                    - { property: 'entrees', type_options: { multiple: true, by_reference: false }}
                    - { property: 'plats', type_options: { multiple: true, by_reference: false }}
                    - { property: 'accompagnements', type_options: { multiple: true, by_reference: false }}
                    - { property: 'desserts', type_options: { multiple: true, by_reference: false }}
                    - users
                    - menuOfCantine


        MenuSelectionne:
            class: App\Entity\MenuSelectionne

    design:
        assets:
            favicon: '/img/backend/appli/four-couteau.png'


    site_name: '<img style="float:right" src="/img/backend/appli/four-couteau.png" /><p>Bienvenue sur le Gestionnaire de</p><b>Cantine 0 Gaspi</b>'